---

# Project name
name: rusty-links

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rusty-links-app
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${DB_USERNAME:-rustylinks}:${DB_PASSWORD:-changeme}@db:5432/${DB_NAME:-rustylinks}
      APP_PORT: 8080
      UPDATE_INTERVAL_DAYS: ${UPDATE_INTERVAL_DAYS:-30}
      UPDATE_INTERVAL_HOURS: ${UPDATE_INTERVAL_HOURS:-24}
      BATCH_SIZE: ${BATCH_SIZE:-50}
      JITTER_PERCENT: ${JITTER_PERCENT:-20}
      RUST_LOG: ${RUST_LOG:-info}
    volumes:
      - rusty-links-app-data:/data
    ports:
      - "${HOST_PORT:-8080}:8080"
    networks:
      - rusty-links-private

  db:
    # https://hub.docker.com/_/postgres
    # https://github.com/docker-library/postgres
    image: docker.io/postgres:17.2-alpine
    container_name: rusty-links-db
    restart: unless-stopped
    healthcheck:
      # See the README for healthcheck information.
      test: [
        "CMD-SHELL",
        "pg_isready -U rustylinks || exit 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
      start_interval: 1s
    environment:
      POSTGRES_USER: ${DB_USERNAME:-rustylinks}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_DB: ${DB_NAME:-rustylinks}
    volumes:
      - ./data/db/:/var/lib/postgresql/data
      # Use this with the volume below change the location of the database.
      #- rusty-links-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rusty-links-private

volumes:
  rusty-links-app-data:
    name: rusty-links-app-data
#  rusty-links-db-data:
#    name: rusty-links-db-data
#    driver_opts:
#      type: none
#      o: bind
#      device: /full/path/to/rusty-link/db/data

networks:
  rusty-links-private:
    name: rusty-links-private
    driver: bridge
