# Configure Dioxus
# https://dioxuslabs.com/learn/0.7/guides/tools/configure

[application]
# App name
name = "rusty-links"

# Dioxus App Default Platform
default_platform = "fullstack"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]
# HTML title tag content
title = "Rusty Links"

[web.watcher]
# when watcher trigger, regenerate the `index.html`
reload_html = true

# If enabled, Dioxus will serve the root page when a route is not found. This is needed when serving an application
# that uses the router. However, when serving your app using something else than Dioxus (e.g. GitHub Pages), you
# will have to check how to configure it on that platform. In GitHub Pages, you can make a copy of index.html
# named 404.html in the same directory.
#index_on_404 = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]
# Public directory to serve static files from
public_dir = "assets"

# CSS style file - handled via asset!() macro in App component
style = []

# Javascript code file
script = []

[web.resource.dev]
# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.rustylinks.app"
publisher = "Rusty Links"
